# Variable Standardization

In [3]:
import numpy as np
import pandas as pd
v1 = np.array([1, 3, 6, 5, 7])
v2 = np.array([7, 7, 5, 8, 12])
v3 = np.array([6, 12, 5, 6, 14])
df = pd.DataFrame({
    "v1": v1,
    "v2": v2,
    "v3": v3,
})

df = df.astype(float)
df

v1    v2    v3
0  1.0   7.0   6.0
1  3.0   7.0  12.0
2  6.0   5.0   5.0
3  5.0   8.0   6.0
4  7.0  12.0  14.0

## Standardization

In [14]:
from sklearn import preprocessing

In [15]:
preprocessing.scale(df)

array([[-1.57841037, -0.34554737, -0.70920814],
       [-0.64993368, -0.34554737,  0.92742603],
       [ 0.74278135, -1.2094158 , -0.98198051],
       [ 0.27854301,  0.08638684, -0.70920814],
       [ 1.2070197 ,  1.81412369,  1.47297076]])

In [16]:
df.mean()

v1    4.4
v2    7.8
v3    8.6
dtype: float64

## Normalization

In [17]:
preprocessing.normalize(df)

array([[0.10783277, 0.75482941, 0.64699664],
       [0.21107926, 0.49251828, 0.84431705],
       [0.64699664, 0.53916387, 0.53916387],
       [0.4472136 , 0.71554175, 0.53665631],
       [0.35491409, 0.60842415, 0.70982818]])

## Min-Max Scaling

In [26]:
preprocessing.MinMaxScaler(feature_range=(100, 200)).fit_transform(df)

array([[  0.        ,  57.14285714,  22.22222222],
       [ 66.66666667,  57.14285714, 155.55555556],
       [166.66666667,   0.        ,   0.        ],
       [133.33333333,  85.71428571,  22.22222222],
       [200.        , 200.        , 200.        ]])