# Creating NumPy Arrays

In [2]:
import numpy as np

In [3]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [4]:
a = np.array([1, 2, 3, 4, 5])

In [5]:
b = np.array([3.1, 3, 6, 7.8], dtype="int")
b

array([3, 3, 6, 7])

## Creating An Array from Zero

In [6]:
np.zeros(10, dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
np.ones((3, 5), dtype="int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [8]:
np.full((3, 5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [9]:
np.arange(0, 31, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [10]:
np.random.normal(10, 4, (3, 4))

array([[ 8.18943241, 18.44747878,  6.41728011,  8.71718264],
       [ 9.34029249, 14.79080627, 14.25118738, 10.18242018],
       [10.061263  , 15.1014666 , 14.0445617 ,  6.00922097]])

In [11]:
np.random.randint(0, 10)

6

In [12]:
np.random.randint(0, 10, size=(3, 5))

array([[2, 9, 6, 6, 8],
       [7, 7, 3, 3, 8],
       [4, 5, 8, 4, 0]])