# Array Concatenation in NumPy

In [1]:
import numpy as np

In [7]:
x = np.arange(1, 4)
y = np.arange(4, 7)

In [9]:
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [12]:
z = np.arange(7, 10)

In [13]:
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
a = np.array([[1, 2, 3], 
              [4, 5, 6]])

In [18]:
np.concatenate([a, a], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])