# Splitting Arrays

In [2]:
import numpy as np

In [9]:
x = [1, 2, 3, 56, 65, 3, 2, 1]

In [11]:
a, b, c = np.split(x, [3, 5])

In [12]:
a

array([1, 2, 3])

In [13]:
b

array([56, 65])

In [14]:
c

array([3, 2, 1])

## Two Dimensional Splitting

In [44]:
m = np.arange(16).reshape(4, 4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [55]:
top, bottom = np.vsplit(m, [2])

In [56]:
left, right = np.hsplit(m, [2])