# Splitting Arrays

In [2]:
import numpy as np

In [3]:
x = [1, 2, 3, 56, 65, 3, 2, 1]

In [4]:
a, b, c = np.split(x, [3, 5])

In [5]:
a

array([1, 2, 3])

In [6]:
b

array([56, 65])

In [7]:
c

array([3, 2, 1])

## Two Dimensional Splitting

In [8]:
m = np.arange(16).reshape(4, 4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
top, bottom = np.vsplit(m, [2])

In [10]:
left, right = np.hsplit(m, [2])

In [11]:
top

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [12]:
bottom

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [14]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])