# Sorting NumPy Arrays

In [1]:
import numpy as np

In [2]:
v = np.arange(1,6)
np.random.shuffle(v)

In [3]:
v

array([2, 1, 3, 4, 5])

In [4]:
v.sort()

In [5]:
v

array([1, 2, 3, 4, 5])

In [6]:
np.random.shuffle(v)

In [7]:
v

array([5, 3, 4, 2, 1])

In [13]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [14]:
v

array([5, 3, 4, 2, 1])

In [9]:
m = np.random.normal(20, 5, (3,3))

In [10]:
m

array([[23.58939387, 12.10897352, 17.97208232],
       [23.80130407, 15.69190137, 23.46952753],
       [14.33805931, 18.27801602, 23.59300282]])

In [11]:
np.sort(m, axis = 1)

array([[12.10897352, 17.97208232, 23.58939387],
       [15.69190137, 23.46952753, 23.80130407],
       [14.33805931, 18.27801602, 23.59300282]])

In [12]:
np.sort(m, axis = 0)

array([[14.33805931, 12.10897352, 17.97208232],
       [23.58939387, 15.69190137, 23.46952753],
       [23.80130407, 18.27801602, 23.59300282]])