# Indexing Arrays

In [4]:
import numpy as np

In [5]:
a = np.random.randint(2, 20, size = 10)
a

array([12,  4,  2, 13, 16,  8, 18, 11,  5,  5])

In [6]:
a[0]

12

In [7]:
a[-1]

5

In [8]:
a[0] = 9

In [9]:
a

array([ 9,  4,  2, 13, 16,  8, 18, 11,  5,  5])

In [10]:
m = np.random.randint(10, size=(3,5))
m

array([[9, 2, 1, 3, 5],
       [8, 2, 9, 4, 2],
       [8, 9, 9, 4, 0]])

In [11]:
m[0, 0]

9

In [12]:
m[0, 4]

5