# Slice Operations

In [2]:
import numpy as np

In [3]:
a = np.arange(20,30) 

In [4]:
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [5]:
a[0:3]

array([20, 21, 22])

In [6]:
a[:3]

array([20, 21, 22])

In [7]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [8]:
a[::2]

array([20, 22, 24, 26, 28])

### Two Dimensional Slice Operations

In [9]:
m = np.random.randint(10, size=(5, 5))

In [10]:
m

array([[3, 7, 8, 0, 3],
       [6, 0, 2, 3, 9],
       [5, 5, 0, 9, 1],
       [4, 0, 2, 9, 0],
       [5, 8, 7, 6, 4]])

In [11]:
m[:,0]

array([3, 6, 5, 4, 5])

In [12]:
m[0,:]

array([3, 7, 8, 0, 3])

In [13]:
m[:2,:3]

array([[3, 7, 8],
       [6, 0, 2]])