# Slice Operations

In [14]:
import numpy as np

In [15]:
a = np.arange(20,30) 

In [16]:
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [17]:
a[0:3]

array([20, 21, 22])

In [18]:
a[:3]

array([20, 21, 22])

In [19]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [20]:
a[0::2]

array([20, 22, 24, 26, 28])

### Two Dimensional Slice Operations

In [21]:
m = np.random.randint(10, size=(5, 5))

In [22]:
m

array([[5, 4, 4, 7, 2],
       [2, 4, 6, 1, 0],
       [9, 5, 7, 6, 7],
       [6, 3, 2, 2, 3],
       [3, 5, 3, 7, 5]])

In [23]:
m[:,0]

array([5, 2, 9, 6, 3])

In [29]:
m[0,:]

array([5, 4, 4, 7, 2])

In [30]:
m[:2,:3]

array([[5, 4, 4],
       [2, 4, 6]])