# Operations on Independent Subsets

In [ ]:
import numpy as np

In [ ]:
a = np.random.randint(10, size = (3, 3))

In [ ]:
a

array([[6, 1, 1],
       [9, 8, 0],
       [9, 3, 0]])

In [7]:
sub_a = a[0:2, 0:2]

In [8]:
sub_a

array([[6, 1],
       [9, 8]])

In [9]:
sub_a[0, 0] = 20

In [10]:
a

array([[20,  1,  1],
       [ 9,  8,  0],
       [ 9,  3,  0]])

##### ! We noticed that if we change a value of subset it makes change the that value on set

In [11]:
m = np.random.randint(10, size = (3, 3))
m

array([[3, 4, 4],
       [1, 6, 6],
       [4, 9, 8]])

In [12]:
alt_m = m[0:2, 0:2].copy()

In [13]:
alt_m

array([[3, 4],
       [1, 6]])

In [14]:
alt_m[0,0] = 20

In [15]:
m

array([[3, 4, 4],
       [1, 6, 6],
       [4, 9, 8]])

In [16]:
alt_m

array([[20,  4],
       [ 1,  6]])

##### ! If we use the copy function we can prevent that change in actual set