# Getting Elements with Fancy Index

In [27]:
import numpy as np

In [28]:
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [29]:
indexes = [1, 3, 5]

In [30]:
v[indexes]

array([ 3,  9, 15])

### Using Fancy Indexes in Two Dimensional Matrices

In [31]:
m = np.arange(0, 30).reshape(5, 6)
m

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [32]:
rows = np.array([0, 1])
columns = np.array([2, 4])

In [33]:
m[rows, columns]

array([ 2, 10])

### Basic Index and Fancy Index

In [34]:
m

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [35]:
m[0, [1, 2]]

array([1, 2])

### Fancy Indexes with Slice Operations

In [36]:
m[:, [1, 3]]

array([[ 1,  3],
       [ 7,  9],
       [13, 15],
       [19, 21],
       [25, 27]])

In [37]:
m[:, 1:3]

array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20],
       [25, 26]])