# Mathematical Operations

###### !!! UFunc

In [1]:
import numpy as np

In [2]:
v = np.arange(1, 6)
v

array([1, 2, 3, 4, 5])

In [3]:
v - 1

array([0, 1, 2, 3, 4])

In [4]:
v / 2

array([0.5, 1. , 1.5, 2. , 2.5])

In [5]:
v % 5

array([1, 2, 3, 4, 0], dtype=int32)

In [6]:
np.log(v)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [7]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ])