# Creating NumPy Arrays

In [2]:
import numpy as np

In [4]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [6]:
a = np.array([1, 2, 3, 4, 5])

In [21]:
b = np.array([3.1, 3, 6, 7.8], dtype="int")
b

array([3, 3, 6, 7])

## Creating An Array from Zero

In [26]:
np.zeros(10, dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
np.ones((3, 5), dtype="int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [30]:
np.full((3, 5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [31]:
np.arange(0, 31, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [36]:
np.random.normal(10, 4, (3, 4))

array([[14.54182053,  8.23064311, 11.1832931 , 10.72651732],
       [ 8.69834903, 11.78333955,  2.06802322,  9.86750595],
       [13.76905379, 10.41697943,  6.44918726, 18.39845497]])

In [38]:
np.random.randint(0, 10, (4, 2))

array([[5, 0],
       [5, 9],
       [2, 2],
       [4, 7]])