# Sorting NumPy Arrays

In [1]:
import numpy as np

In [7]:
v = np.arange(1,6)
np.random.shuffle(v)

In [6]:
v

array([4, 3, 5, 2, 1])

In [10]:
v.sort()

In [11]:
v

array([1, 2, 3, 4, 5])

In [12]:
np.random.shuffle(v)

In [13]:
v

array([3, 2, 1, 4, 5])

In [14]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [15]:
m = np.random.normal(20, 5, (3,3))

In [16]:
m

array([[ 9.4937873 , 16.73340228, 26.3563826 ],
       [23.29661251, 20.45513627, 25.35850092],
       [19.4254832 , 12.97629511, 19.652949  ]])

In [17]:
np.sort(m, axis = 1)

array([[ 9.4937873 , 16.73340228, 26.3563826 ],
       [20.45513627, 23.29661251, 25.35850092],
       [12.97629511, 19.4254832 , 19.652949  ]])

In [18]:
np.sort(m, axis = 0)

array([[ 9.4937873 , 12.97629511, 19.652949  ],
       [19.4254832 , 16.73340228, 25.35850092],
       [23.29661251, 20.45513627, 26.3563826 ]])