# Indexing Arrays

In [14]:
import numpy as np

In [15]:
a = np.random.randint(10, size = 10)
a

array([1, 1, 4, 8, 5, 0, 2, 8, 1, 7])

In [16]:
a[0]

1

In [17]:
a[-1]

7

In [20]:
a[0] = 9

In [21]:
a

array([9, 1, 4, 8, 5, 0, 2, 8, 1, 7])

In [23]:
m = np.random.randint(10, size=(3,5))
m

array([[3, 3, 3, 9, 8],
       [3, 1, 9, 8, 6],
       [3, 7, 0, 0, 0]])

In [24]:
m[0, 0]

3

In [25]:
m[0, 4]

8