# Conditional Operations

In [1]:
import numpy as np

In [3]:
v = np.array([1, 2, 3, 4, 5])
v

array([1, 2, 3, 4, 5])

In [4]:
v > 5

array([False, False, False, False, False])

In [5]:
v < 3

array([ True,  True, False, False, False])

In [6]:
v == 2

array([False,  True, False, False, False])

### Fancy Index with Logical Operations

In [10]:
v[v < 3]

array([1, 2])

In [11]:
v[v >= 2]

array([2, 3, 4, 5])

In [12]:
v[v != 3]

array([1, 2, 4, 5])

In [15]:
v * 2

array([ 2,  4,  6,  8, 10])

In [16]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [19]:
v ** 2

array([ 1,  4,  9, 16, 25], dtype=int32)