# Equations with Two Unknowns

In [1]:
import numpy as np

5a + b = 12

a + 3b = 10

In [3]:
m = np.array([[5, 1], [1,3]])
n = np.array([12, 10])

In [4]:
m

array([[5, 1],
       [1, 3]])

In [5]:
n

array([12, 10])

In [9]:
result = np.linalg.solve(m, n)

In [10]:
result

array([1.85714286, 2.71428571])